server: Correct prameter type for connect() API
connect() function expects the second argument to be point to sockaddr
as per man sockaddr

int connect (int, const struct sockaddr *, socklen_t);

Fixes build failures with -Wincompatible-pointer-types when using GCC-14
and musl

Fixes
| server.c: In function 'server_ping':
| server.c:308:33: error: passing argument 2 of 'connect' from incompatible pointer type [-Wincompatible-pointer-types]
|   308 |                 if (connect(fd, un, sizeof(struct sockaddr_un)) < 0)
|       |                                 ^~
|       |                                 |
|       |                                 struct sockaddr_un *

Signed-off-by: Andi Kleen <ak@linux.intel.com>